import type { BurnConfig } from "./config";
import { sha256Hex } from "./tokens";

/**
 * Renders the SQL the user pastes into their Supabase SQL editor AFTER running
 * every numbered supabase migration in order. Registers this
 * environment (ingest token) and the phone (read token) — hashes only.
 */
export function renderSetupSql(input: {
  config: BurnConfig;
  ingestToken: string;
  readToken: string;
  readTokenLabel?: string;
}): string {
  const { config, ingestToken, readToken } = input;
  return `-- burn setup tokens — generated by \`burn-report init\`
-- Paste AFTER every numbered supabase/migrations/*.sql file, in order.
-- Hashes only: the plaintext tokens live in ${"`"}~/.config/burn/config.json${"`"} (this machine)
-- and in the burn app on your phone. Re-run init to rotate.

insert into burn.environments (slug, display_name, host_group, os_kind, ingest_token_hash, reporting_timezone)
values (${sql(config.environmentSlug)}, ${sql(config.environmentName)}, ${sqlNullable(config.hostGroup)}, ${sql(config.osKind)}, '${sha256Hex(ingestToken)}', ${sql(config.reportingTimezone)})
on conflict (slug) do update set
  display_name = excluded.display_name,
  host_group = excluded.host_group,
  os_kind = excluded.os_kind,
  ingest_token_hash = excluded.ingest_token_hash,
  reporting_timezone = excluded.reporting_timezone;

insert into burn.read_tokens (token_hash, label)
values ('${sha256Hex(readToken)}', ${sql(input.readTokenLabel ?? "phone")})
on conflict (token_hash) do nothing;
`;
}

function sql(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlNullable(value: string | null): string {
  return value === null ? "null" : sql(value);
}
